[package]
name = "origin"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "origin"
path = "src/main.rs"

[[bin]]
name = "inspect"
path = "src/bin/inspect.rs"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
blaze-common = { path = "../blaze-common" }
blaze-proto = { path = "../blaze-proto" }
iroh.workspace = true
iroh-relay.workspace = true
redb.workspace = true
serde.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tonic.workspace = true
toml.workspace = true
