[package]
name = "producer"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "producer"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
blake3.workspace = true
blaze-common = { path = "../blaze-common" }
fastcdc.workspace = true
serde.workspace = true
serde_json.workspace = true
toml.workspace = true

[dev-dependencies]
rand.workspace = true
rand_chacha.workspace = true
